#!/usr/bin/env python3
"""Build the browser dictionary for Word Chain Loop from SCOWL v2.

The game accepts only lowercase ASCII English words, so this script deliberately
filters out entries containing spaces, punctuation, apostrophes, digits, or
diacritics after asking SCOWL to de-accent its word list.  It includes every
SCOWL word through size 80 (SCOWL's "a valid word" tier) for the five main
English spelling variants. It preserves SCOWL's original capitalization long
enough to exclude proper names and acronyms, filters flagged offensive terms,
and emits a compact tier marker alongside each word.

Usage:
    python tools/build-dictionary.py --scowl-dir <path-to-scowl-2>

SCOWL source and license: https://github.com/engramtech/scowl
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sqlite3
import subprocess
import sys
from datetime import date
from pathlib import Path


ASCII_WORD = re.compile(r"^[a-z]{3,}$")
ROOT = Path(__file__).resolve().parents[1]


def read_scowl(scowl_dir: Path, size: int) -> set[str]:
    command = [
        sys.executable,
        str(scowl_dir / "scowl"),
        "word-list",
        str(scowl_dir / "scowl.db"),
        "--size",
        str(size),
        "--spellings",
        "A,B,Z,C,D",
        "--variant-level",
        "4",
        "--wo-poses",
        "abbr,s",
        "--categories",
        "",
        "--deaccent",
        "--nosuggest",
    ]
    result = subprocess.run(command, check=True, capture_output=True)
    text = result.stdout.decode("utf-8", errors="ignore")
    # Match before lowercasing. Capitalized SCOWL entries are normally proper
    # names or acronyms and are unsuitable for standard word-game play.
    return {word for word in text.splitlines() if ASCII_WORD.fullmatch(word)}


def read_lemma_data(scowl_dir: Path) -> tuple[set[str], dict[str, str]]:
    """Return canonical lemmas and a preferred word-to-lemma mapping."""
    lemmas: set[str] = set()
    lemma_map: dict[str, str] = {}
    with sqlite3.connect(scowl_dir / "scowl.db") as connection:
        rows = connection.execute(
            "select word.word, lemma.word "
            "from words as word join words as lemma on word.lemma_id = lemma.word_id"
        )
        for word, lemma in rows:
            if not ASCII_WORD.fullmatch(word) or not ASCII_WORD.fullmatch(lemma):
                continue
            if word == lemma:
                lemmas.add(word)
                lemma_map.setdefault(word, word)
            elif word not in lemma_map or lemma_map[word] == word:
                lemma_map[word] = lemma
    return lemmas, lemma_map


def base36_fixed(value: int, width: int = 4) -> str:
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    encoded = "0" if value == 0 else ""
    while value:
        value, remainder = divmod(value, 36)
        encoded = digits[remainder] + encoded
    if len(encoded) > width:
        raise ValueError("dictionary index no longer fits the fixed-width lemma encoding")
    return encoded.rjust(width, "0")


def write_output(
    words: list[str], tiers: str, forms: str, starts: str,
    lemma_ids: str, tier_counts: dict[str, int]
) -> None:
    word_json = json.dumps(words, ensure_ascii=False, separators=(",", ","))
    meta_json = json.dumps(
        {"tierNames": ["common", "standard", "extended"], "counts": tier_counts},
        ensure_ascii=False,
        separators=(",", ":"),
    )
    output = ROOT / "dictionary.js"
    output.write_text(
        "// Generated by tools/build-dictionary.py; do not edit by hand.\n"
        "// Source: SCOWL v2, sizes 60/70/80, all main English spellings.\n"
        "// License and update procedure: DICTIONARY_SOURCES.md\n"
        f"// Generated: {date.today().isoformat()}; words: {len(words)}.\n"
        f"var DICTIONARY={word_json};\n"
        f"var WORD_TIERS={json.dumps(tiers)};\n"
        f"var WORD_FORMS={json.dumps(forms)};\n"
        f"var WORD_STARTS={json.dumps(starts)};\n"
        f"var WORD_LEMMA_IDS={json.dumps(lemma_ids)};\n"
        f"var DICTIONARY_META={meta_json};\n",
        encoding="utf-8",
        newline="\n",
    )
    report = {
        "source": "SCOWL v2",
        "scowl_size": 80,
        "spellings": ["American", "British -ise", "British -ize", "Canadian", "Australian"],
        "word_count": len(words),
        "tier_counts": tier_counts,
        "lemma_count": sum(mark == "0" for mark in forms),
        "start_vocabulary_count": sum(mark == "1" for mark in starts),
        "minimum_length": min(map(len, words)),
        "maximum_length": max(map(len, words)),
        "generated_on": date.today().isoformat(),
    }
    (ROOT / "dictionary-report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n"
    )


def copy_license_notice(scowl_dir: Path) -> None:
    """Ship SCOWL's upstream notice alongside every derived word list."""
    notices = ROOT / "THIRD_PARTY_NOTICES"
    notices.mkdir(exist_ok=True)
    shutil.copyfile(scowl_dir / "Copyright", notices / "SCOWL-Copyright.txt")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Word Chain Loop's SCOWL-based dictionary.")
    parser.add_argument("--scowl-dir", type=Path, required=True, help="Path to an unpacked SCOWL v2 checkout")
    args = parser.parse_args()
    scowl_dir = args.scowl_dir.resolve()
    if not (scowl_dir / "scowl").is_file() or not (scowl_dir / "scowl.db").is_file():
        parser.error("--scowl-dir must contain both scowl and scowl.db")
    start_core = read_scowl(scowl_dir, 35)
    common = read_scowl(scowl_dir, 60)
    standard = read_scowl(scowl_dir, 70)
    extended = read_scowl(scowl_dir, 80)
    lemmas, lemma_map = read_lemma_data(scowl_dir)
    if not extended:
        raise RuntimeError("SCOWL extraction returned no usable words")
    words = sorted(extended)
    tiers = "".join("0" if word in common else "1" if word in standard else "2" for word in words)
    forms = "".join("0" if lemma_map.get(word, word) == word else "1" for word in words)
    starts = "".join(
        "1" if word in start_core and lemma_map.get(word, word) == word else "0"
        for word in words
    )
    word_indexes = {word: index for index, word in enumerate(words)}
    lemma_ids = "".join(
        base36_fixed(word_indexes.get(lemma_map.get(word, word), index))
        for index, word in enumerate(words)
    )
    tier_counts = {
        "common": sum(mark == "0" for mark in tiers),
        "standard": sum(mark == "1" for mark in tiers),
        "extended": sum(mark == "2" for mark in tiers),
    }
    write_output(words, tiers, forms, starts, lemma_ids, tier_counts)
    copy_license_notice(scowl_dir)
    print(f"Wrote {len(words):,} filtered and tiered words to {ROOT / 'dictionary.js'}")


if __name__ == "__main__":
    main()
